### ISSUE TITLE
Fur shader fins generation not working

### ISSUE THREAD

**Issue by HENDRIX-ZT2** [OpenNaja/cobra-blender#1]
Functional for edited stock models, can not be generated in functional form from scratch at the moment.

**Comment by harlequinzeg0** [comment]
going to look into this this week by checking a single polygon or two from stock fins against generated polygon

**Comment by harlequinzeg0** [comment]
UV1 vertical controls the fin length, starting at 1.00049 downwards, horizontal controls start position and tiling of the fin texture  starting at -16 going rightwards,

**Comment by harlequinzeg0** [comment]
The generate fins  script erroneously applied the fur length weight from the shell mesh to the fin mesh causing it to glitch out ingame

next revision of the code will properly generate custom fins and have both custom and stock fins export properly
