### ISSUE TITLE
generated fin length unaffected by the fur_length weight parameter

### ISSUE THREAD

**Issue by SleepyEngi** [OpenNaja/cobra-blender#10]
no matter what your fur_length is set to, the fins always generate at the same height.

**Comment by HENDRIX-ZT2** [comment]
This is sort of intended behavior as length is only applied to uv layer 1. We only extrude the geometry so it shows up in blender. Remember the generated fur still doesn't work ingame as fins. Extrusion length that seems to be ignored completely ingame even if the tips of stock fins are moved about a bit (the position of the bases does matter, tho).
