### ISSUE TITLE
Export error about JWE Dilophosaurus model

### ISSUE THREAD

**Issue by MrOuija99** [OpenNaja/cobra-blender#11]
Hey there,
I'm trying to mod around for Jurassic World Evolution and now tried to do the Dilophosaurus. 
I'm working on Blender v. 2.81.16, have the newest Version of Cobra Blender and Cobra Tools 1.4.2. 

I wanted to fix the teeth on the animal. However, when I remove the teeth and want to Export the model, I get this ![error](https://user-images.githubusercontent.com/60053061/72673808-7cee6300-3a6f-11ea-8bbb-1c19e5a722de.jpg)

This error happens only with that dinosaur. I've tested other things out and streched some bodyparts etc. and the Export worked, but when I delete only one tooth, this error popps up and Blender shuts down. Dunno why is that.

**Comment by HENDRIX-ZT2** [comment]
Oh boy, I finally found the source of this error :)
It was much simpler than expected!
