### ISSUE TITLE
Slightly distorted models ingame

### ISSUE THREAD

**Issue by MrOuija99** [OpenNaja/cobra-blender#12]
Hey the update works super fine! Now the export works. Thank you for fixing it! :)
But there is one little ting: I have some little glitch, that I never had in the older Blender version.
When exporting the model and then then try it ingame, the model looks kinda "rumpled".
Here are two Pictures as a example:
![example_1](https://user-images.githubusercontent.com/60053061/72953954-1d59c580-3d97-11ea-8d3f-ba9d2bb1f5d6.jpg)
![example_2](https://user-images.githubusercontent.com/60053061/72953955-1df25c00-3d97-11ea-9073-d27830be76a3.jpg)

It Looks weird. As if I messed up the mesh, what I didn't (as you can see in the blender pics). The same thing happens with the Spinosaurus: I have a 2.79 blend file, where I previously worked on the animal, exported it and the ingame model worked fine. Howeve, when I open it in the 2.81 version, do some tweaks and export it, the model also Looks "rumpled", too.
I dunno, this Problem happened now to those two animals. I worked on other models like the Raptors and the rex and never had this kind of Problem ingame. Is this more a cobra-blender thing or cobra-tools? I was not sure. Do I something wrong?

Thanks in advance!

**Comment by HENDRIX-ZT2** [comment]
Two things:
1) Don't migrate blend files from blender 2.79 to 2.81 like that. Start out with a stock MDL2 and import that into 2.81 again, and see if the issue persists.
2) See if the same distortion also occurs in blender if you re-import the exported modified model.

**Comment by MrOuija99** [comment]
Thanks for your quick answer! I've tested it out: I've exported a new MDL2 from the newest ovl_tool, opened it on Blender 2.81, edited it the way I wanted, exported the model and imported it into the ovl file. I've opened the game and the same Thing happens. The model looks "rumpled" again.

**Comment by HENDRIX-ZT2** [comment]
How does it look when you re-import it into blender? Crumpled or as intended?

**Comment by HENDRIX-ZT2** [comment]
Also please try the same with this version of the plugin:
[cobra-blender.zip](https://github.com/OpenNaja/cobra-blender/files/4102607/cobra-blender.zip)

**Comment by MrOuija99** [comment]
Even with the new plugin it's the same bug. Unpacked a new clean MDL2, Import in Blender, edit, export, inject and ingame.

**Comment by HENDRIX-ZT2** [comment]
Ok. Now what I want you to do is:
Import a model into blender.
Make edits.
Export model, do not close blender.
Import the model you have just imported into same blend file / scene.
Compare the newly imported version to the one you had originally exported it from.
Are they vertices in the exact same spots for both meshes or is the newly imported one crumpled too?

**Comment by MrOuija99** [comment]
Okay I tried it out:
The models look exactly the same. So I guess it's not a export issue with the cobra-blender.
![exampöe](https://user-images.githubusercontent.com/60053061/72981691-af84bc80-3ddd-11ea-8a65-016bd1dacba4.jpg)

It's weird. I never had these kinda issue in the 2.79 build.

**Comment by HENDRIX-ZT2** [comment]
Right that's the weird thing. A lot of stuff was rewritten from the ground up for 2.8 so it works for more model types. Got to figure out where the bug is creeping in...

Another thing you can test, variation of the last test:
Instead of importing the freshly exported model into blender, do the following:
Inject the exported model into the OVL and then unpack it again. Import the newly unpacked version of the exported model and compare with 'first version'. Crumpled or not?

**Comment by MrOuija99** [comment]
No it's not crumpled. It Looks exactly the same.

**Comment by HENDRIX-ZT2** [comment]
Fixed, was lacking normalization of vertex weights to 255.
