### ISSUE TITLE
Question about mdl2 and ms2 file

### ISSUE THREAD

**Issue by sehmvstekn** [OpenNaja/cobra-blender#17]
I have a question, how can I combine the mdl2 file with the ms2 file in blender?

**Comment by HENDRIX-ZT2** [comment]
Not sure what you mean. Mdl2 is only linking information into the ms2 model buffer. Edited mdl2/ms2 pairs are automatically integrated with the other models when you inject them into an ovl archive.

**Comment by sehmvstekn** [comment]
In the explanation part, you’ve mentioned to merge mdl2 file to ms2 , I was asking about that, I,ve arranged that as mdl2 file but I couldn’t merge it with ms2 , could you help me about that?

**Comment by HENDRIX-ZT2** [comment]
You no longer merge them manually (merger tool has been removed), now merging happens on the fly when you inject your exported models in the OVL tool.
