### ISSUE TITLE
MDL2 importing issue!

### ISSUE THREAD

**Issue by Lukiethewesly13** [OpenNaja/cobra-blender#20]
I'm confused with how to import the image at the bottom is all what shows up when I try to import it. It it something I have to do with pyffi. Is it something about pyffi_ext.

![Import issue](https://user-images.githubusercontent.com/60950635/77600651-ef037e00-6ede-11ea-9ba4-c244c295ad69.png)

**Comment by HENDRIX-ZT2** [comment]
You did not install pyffi (not pyffi_ext) for blender's python. There are several ways, follow the instructions [here](https://github.com/OpenNaja/cobra-blender) or the tutorial [here](https://docs.google.com/document/d/1IBG-QTyi-96dgB7MDwDJTqMZ-s31-mHgqerW40k3bnY/edit)
