### ISSUE TITLE
This is just a question but...

### ISSUE THREAD

**Issue by Lukiethewesly13** [OpenNaja/cobra-blender#21]
Is there a way to also have the dinosaur texture with the detail scales. Because that's the only thing I wanna do.

**Comment by HENDRIX-ZT2** [comment]
via blender, sort of

**Comment by Lukiethewesly13** [comment]
> 
> 
> via blender, sort of

How, is that what matcol file is for?

**Comment by HENDRIX-ZT2** [comment]
exactly

**Comment by Lukiethewesly13** [comment]
OH! Okay I know how to import it now, but there's an error when I try to import the matcol.

**Comment by Lukiethewesly13** [comment]
https://i.pinimg.com/originals/13/99/05/1399052853511ad48c73dd2eea2db5ce.png this shows up instead.

**Comment by HENDRIX-ZT2** [comment]
You must unpack a certain OVL into that folder, I think it was called DinosaurCommon.ovl or something. Idk, better ask on discord
