### ISSUE TITLE
Can't install addon

### ISSUE THREAD

**Issue by magicdog2013games** [OpenNaja/cobra-blender#24]
Basically I get an error when I press the enable button: `Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'cobra-blender-1' 
Any ideas how to fix it

`

**Comment by HENDRIX-ZT2** [comment]
Did you download the release build?

**Comment by magicdog2013games** [comment]
The most recent, yes

**Comment by magicdog2013games** [comment]
> Did you download the release build?

the most recent, yes

**Comment by HENDRIX-ZT2** [comment]
It's never called cobra-blender-1
What's the name of the zip file you downloaded/installed?

**Comment by magicdog2013games** [comment]
> It's never called cobra-blender-1
> What's the name of the zip file you downloaded/installed?

I just redownloaded it and the file name was different for some reason and it worked, I dunno why but okay
