### ISSUE TITLE
Idfk what to do man

### ISSUE THREAD

**Issue by brendanj01** [OpenNaja/cobra-blender#29]
Hey can someone snap me or something @brendan_j01 asap and walk me through this ive been trying to edit a dino model for hours but everytime i try to import a dino file (.mld2 or something like that) it tells me a bunch of shit ive seen ppl having the same problem but i havent seen an actual solution, i have the latest update for blender, i have cobra blender and cobra tool of course, latest update of jurassic world evolution, i think my pythons like 3.9 or something and im screwed with the pyffi shit, i have downloaded pyffi or whatever and i thought i installed it correctly but someone call me or snap me please and walk me through this.

**Comment by HENDRIX-ZT2** [comment]
Just nope. Try again nicely and well documented. Or ask on discord.

**Comment by brendanj01** [comment]
wym nicely??? I was!! wtf
