### ISSUE TITLE
Jurassic World Evolution Building Modeling

### ISSUE THREAD

**Issue by brendanj01** [OpenNaja/cobra-blender#30]
Hey I was looking for some advice on building editing for Jurassic World Evolution. I can import the building models into Blender and edit them to look the way I want and I can also import them into the game fine but the changes I made to the building dont show up in game unless I zoom into them. But when Im zoomed out they restore to original models. I can model dinosaurs fine though. Please let me know what could help, thank you.

**Comment by harlequinzeg0** [comment]
need to update the other lod levels
